#!/bin/bash
#
# chkconfig: 2345 10 5
# description: Starts the docke registry server
#
# Source function library.

. /etc/init.d/functions
PATH=/sbin:/bin:/usr/sbin:/usr/bin:$PATH
RETVAL=0
DREG=docker-registry

start(){
	if [ -f /var/lock/subsys/$DREG ]; then
		echo "docker-registry is running"
	else
		echo "docker-registry is starting"
		nohup gunicorn --access-logfile /var/log/docker-registry/access.log --error-logfile /var/log/docker-registry/server.log -k gevent --max-requests 100 --graceful-timeout 3600 -t 3600 -b 0.0.0.0:5000 -w 1 docker_registry.wsgi:application -p /var/run/docker-registry.pid 2>dev/null &
		touch /var/lock/subsys/docker-registry
		sleep 1
		echo "docker-registry start OK."
	fi
	}
stop(){
	if [ -f /var/lock/subsys/$DREG ];then
		echo "Stopping docker-registry"
  		cat /var/run/docker-registry.pid | while read line;do kill -9 $line; done
		rm -f /var/lock/subsys/docker-registry
		rm -f /var/run/docker-registry.pid
		sleep 1
		echo "docker-registry stop OK."
	else
		echo "docker-registry is not running"
	fi
	}
restart(){
	stop
	start
	}
case "$1" in
	start)
		start;;
	stop)
		stop;;
	restart)
		restart;;
	*)
	echo $"Usage: ${DREG} {start|stop|restart}"
	exit 1 ;;
esac
exit $RETVAL
